service: swda-etf-crash-alert

frameworkVersion: "4"

provider:
  name: aws
  profile: tobias
  runtime: python3.10
  region: eu-south-1

package:
  individually: true
  exclude:
    - ./**

functions:
  modules:
  checkBollingerBands:
    handler: handler.handler
    memorySize: 128
    timeout: 120
    package:
      include:
        - handler.py
    events:
      - schedule: cron(0 11 ? * MON-FRI *)
